### ISSUE TITLE
"Get direct link" button issue

### ISSUE THREAD

**Issue by villares** [pycomic/pycomic.github.io#3]
This is such a wonderful thing!

Looks like "Get direct link" is not working anymore, at least for me. As it was created a long time ago, I wonder if there is any chance for an easy fix to it. I really understand if there is no energy left available to fix this.

Cheers!

![image](https://user-images.githubusercontent.com/3694604/101263157-f5aaec00-3721-11eb-80f7-b5c4ccbf142f.png)

**Comment by ntoll** [comment]
@villares thank you for letting me know. It looks like rebrandly.com have changed their API.

I notice that tinyurl.com might be a good alternative: e.g. https://tinyurl.com/api-create.php?url=google.com

**Comment by ntoll** [comment]
OK 8b18109 should fix it. Give it 10 mins for GitHub pages to recycle and try again. I'll close this (I tested it works when run locally), but if it's not fixed when the live site updates, please feel free to reopen. Thanks for reporting it..! :-)

**Comment by villares** [comment]
https://pycomic.github.io/?title=Python%20Comic&author=%20&h1=And%20then...&h2=Nicholas%20Tollervey%20fixed%20it.&h3=and%20we%20are%20back!&bg1=bg%2Farm1_chip.gif&bg2=bg%2Fmoon.jpg&bg3=bg%2Fpython_powered.jpg&s3=blue&rb3=pycomic.github.io%20share%20button%20is%20back!

UPDATE: ops... there was a typo...
